snippet_support = false
verbosity = 1

[server]
timeout = 1800 # seconds = 30 minutes


[language.c_cpp]
filetypes = ["c", "cpp"]
roots = ["compile_commands.json", ".clangd", ".git", ".hg"]
command = "clangd"
offset_encoding = "utf-8"


[language.python]
filetypes = ["python"]
roots = ["requirements.txt", "setup.py", ".git", ".hg"]
command = "pylsp"
offset_encoding = "utf-8"
workaround_server_sends_plaintext_labeled_as_markdown = true
settings_section = "_"
[language.python.settings._]
pylsp.configurationSources = ['flake8']
pylsp.plugins.pyflakes.enabled = false
pylsp.plugins.pycodestyle.enabled = false
pylsp.plugins.flake8.enabled = true
pylsp.plugins.flake8.maxLineLength = 200
pylsp.plugins.flake8.ignore = ['E501']
pylsp.plugins.flake8.perFileIgnores = ['__init__.py:F401,F403,F405']


[language.tsx]
command = 'typescript-language-server'
filetypes = ['typescript']
roots = ['package.json']
args = ['--stdio']
settings_section = '_'
[language.tsx.settings._]
preferences.quotePreference = 'single'
preferences.includeCompletionsWithSnippetText = false
