snippet_support = false
verbosity = 2

[server]
timeout = 1800 # seconds = 30 minutes


[language.c_cpp]
filetypes = ["c", "cpp"]
roots = ["compile_commands.json", ".clangd", ".git", ".hg"]
command = "clangd"
offset_encoding = "utf-8"


[language.python]
filetypes = ["python"]
roots = ["requirements.txt", "setup.py", ".git", ".hg"]
command = "pylsp"
offset_encoding = "utf-8"
workaround_server_sends_plaintext_labeled_as_markdown = true
settings_section = "_"
